server:
  port: 8088

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: api-ckt3
          uri: lb://api-ckt3
          predicates:
            - Path=/api-ckt3/**
          filters:
            - StripPrefix=1
        - id: project-cuoi-ky
          uri: lb://ProjectCuoiKyT3
          predicates:
            - Path=/project-cuoi-ky/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
